### ISSUE TITLE
Minimal / no extra features version, providing *only* urlbar hiding

### ISSUE THREAD

**Issue by ronjouch** [rstacruz/firefox-stealthfox#2]
Hi and thanks for the CSS! 🙂 (discovered via [reddit](https://www.reddit.com/r/FirefoxCSS/comments/aeh88f/github_rstacruzfirefoxstealthfox_firefox/)).

So far it works for me, but I have a minor gripe: the current userChrome.css is basically your whole userChrome.css, including lots of things that are not related to the core urlbar hiding you advertise, and that might be unwanted by some users, or downright clashing with existing customizations. For example, I don't want touch size, I don't want the tab color tweaks, and I'm happy with the vertical tab separators and the size of the "New Tab" button.

What about offering the current userChrome.css as maybe userChrome_full.css, and limit userChrome.css to the basic functionality? In the current version, I isolated it as:

```css
:root {
  --stealth-fade-in-speed: 100ms;
  --stealth-fade-out-speed: 250ms;
  --bar-height: 40px;
}

#main-window:not([customizing]) #navigator-toolbox {
  overflow: hidden !important;
}

#main-window:not([customizing]) #TabsToolbar,
#main-window:not([customizing]) #nav-bar {
  transition: opacity var(--stealth-fade-out-speed) ease-out,
    transform var(--stealth-fade-out-speed) ease-in !important;
}

#main-window:not([customizing]) #TabsToolbar {
  height: calc(var(--bar-height)) !important;
  transform: translate3d(0, 0, 0) !important;
}

#main-window:not([customizing]) #nav-bar {
  height: calc(var(--bar-height)) !important;
  transform: translate3d(0, calc(-1 * var(--bar-height)), 0) !important;
}

#main-window:not([customizing]) #nav-bar {
  opacity: 0 !important;
  margin-top: calc(-1 * var(--bar-height)) !important;
  pointer-events: none !important;
}

/* Fade-in speed */
#main-window:not([customizing]) #navigator-toolbox:focus-within #nav-bar,
#main-window:not([customizing]) #navigator-toolbox:focus-within #TabsToolbar {
  transition: opacity var(--stealth-fade-in-speed) ease-out,
    transform var(--stealth-fade-in-speed) ease-in !important;
}

#main-window:not([customizing]) #navigator-toolbox:focus-within #nav-bar {
  opacity: 1 !important;
  z-index: 100 !important;
  pointer-events: auto !important;
  transform: translate3d(0, 0, 0) !important;
}

#main-window:not([customizing]) #navigator-toolbox:focus-within #TabsToolbar {
  opacity: 0 !important;
  pointer-events: none !important;
  transform: translate3d(0, calc(0.5 * var(--bar-height)), 0) !important;
}

#main-window:not([customizing]) #tabbrowser-tabs,
#main-window:not([customizing]) #nav-bar {
  background: linear-gradient(
    to bottom,
    transparent,
    rgba(0, 0, 0, 0.03)
  ) !important;
}
```
